"""fix appointment table

Revision ID: 31c57f34f7d7
Revises: d3be20552ba7
Create Date: 2026-02-26 17:01:13.437618

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "31c57f34f7d7"
down_revision: Union[str, Sequence[str], None] = "d3be20552ba7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    # Drop old single-column FK if it still exists
    app_fks = inspector.get_foreign_keys("appointments")
    old_fk = next(
        (fk for fk in app_fks if fk.get("name") == "appointments_patient_user_id_fkey"),
        None,
    )
    if old_fk:
        op.drop_constraint(
            "appointments_patient_user_id_fkey", "appointments", type_="foreignkey"
        )

    # Create composite FK if not already present
    has_composite = any(
        fk
        for fk in inspector.get_foreign_keys("appointments")
        if fk.get("name") == "fk_appointments_patient_tenant_user"
    )
    if not has_composite:
        # Re-read FKs after potential drop
        app_fks2 = sa.inspect(bind).get_foreign_keys("appointments")
        has_composite2 = any(
            fk
            for fk in app_fks2
            if fk.get("name") == "fk_appointments_patient_tenant_user"
        )
        if not has_composite2:
            op.create_foreign_key(
                "fk_appointments_patient_tenant_user",
                "appointments",
                "patients",
                ["tenant_id", "patient_user_id"],
                ["tenant_id", "user_id"],
            )

    # Drop duration_minutes if it exists
    cols = {c["name"] for c in inspector.get_columns("appointments")}
    if "duration_minutes" in cols:
        op.drop_column("appointments", "duration_minutes")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "appointments",
        sa.Column(
            "duration_minutes", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(
        "fk_appointments_patient_tenant_user", "appointments", type_="foreignkey"
    )
    op.create_foreign_key(
        "appointments_patient_user_id_fkey",
        "appointments",
        "patients",
        ["patient_user_id"],
        ["user_id"],
    )
    # ### end Alembic commands ###
