"""add payment table

Revision ID: 52941afd21f8
Revises: 50266c1c58b3
Create Date: 2026-02-24 12:35:43.606254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52941afd21f8'
down_revision: Union[str, Sequence[str], None] = '50266c1c58b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('payment_type', sa.Enum('TENANT_SUBSCRIPTION', 'ENROLLMENT', 'ORDER', 'CONSULTATION', name='payment_type'), nullable=False),
    sa.Column('price', sa.DECIMAL(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('stripe_payment_intent_id', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('INITIATED', 'AUTHORIZED', 'CAPTURED', 'FAILED', 'REFUNDED', name='payment_status'), nullable=False),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('reference_type', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('payment_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    # ### end Alembic commands ###
