"""add lead status history

Revision ID: 540ea65b110c
Revises: 8f330fbb21c2
Create Date: 2026-02-24 02:58:04.812339

"""
from sqlalchemy.dialects import postgresql
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '540ea65b110c'
down_revision: Union[str, Sequence[str], None] = '8f330fbb21c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    op.create_table(
        'lead_status_history',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('lead_id', sa.Integer(), nullable=False),
        sa.Column(
            'old_status',
            postgresql.ENUM(
                'NEW',
                'CONTACTED',
                'DEMO_SCHEDULED',
                'DEMO_COMPLETED',
                'HIGH_INTEREST',
                'NEGOTIATION',
                'CONVERTED',
                'REJECTED',
                name='lead_status',
                create_type=False
            ),
            nullable=True
        ),
        sa.Column(
            'new_status',
            postgresql.ENUM(
                'NEW',
                'CONTACTED',
                'DEMO_SCHEDULED',
                'DEMO_COMPLETED',
                'HIGH_INTEREST',
                'NEGOTIATION',
                'CONVERTED',
                'REJECTED',
                name='lead_status',
                create_type=False
            ),
            nullable=False
        ),
        sa.Column('changed_by_user_id', sa.Integer(), nullable=True),
        sa.Column(
            'changed_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False
        ),
        sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.id']),
        sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lead_status_history')
    # ### end Alembic commands ###
