"""Add cancelled_at and cancellation_reason to tenant_subscriptions

Revision ID: 5a42538a76fa
Revises: i3j4k5l6m7n8
Create Date: 2026-02-28 22:31:49.457283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5a42538a76fa'
down_revision: Union[str, Sequence[str], None] = 'i3j4k5l6m7n8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE IF EXISTS consultation_requests")
    op.add_column('tenant_subscriptions', sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tenant_subscriptions', sa.Column('cancellation_reason', sa.Text(), nullable=True))
    op.drop_constraint('tenant_subscriptions_approved_by_fkey', 'tenant_subscriptions', type_='foreignkey')
    op.drop_column('tenant_subscriptions', 'approved_at')
    op.drop_column('tenant_subscriptions', 'approved_by')
    op.drop_column('tenant_subscriptions', 'terminated_reason')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant_subscriptions', sa.Column('terminated_reason', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('tenant_subscriptions', sa.Column('approved_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tenant_subscriptions', sa.Column('approved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.create_foreign_key('tenant_subscriptions_approved_by_fkey', 'tenant_subscriptions', 'users', ['approved_by'], ['id'])
    op.drop_column('tenant_subscriptions', 'cancellation_reason')
    op.drop_column('tenant_subscriptions', 'cancelled_at')
    op.create_table('consultation_requests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tenant_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('contact_email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('date_of_request', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('preferred_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('pending', 'scheduled', 'completed', 'rejected', name='consultationstatus'), autoincrement=False, nullable=False),
    sa.Column('sales_agent_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['sales_agent_id'], ['users.id'], name='consultation_requests_sales_agent_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='consultation_requests_pkey')
    )
    # ### end Alembic commands ###
