"""add product table

Revision ID: 67f333870a6a
Revises: 7aff676701cb
Create Date: 2026-02-24 12:03:47.576541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67f333870a6a'
down_revision: Union[str, Sequence[str], None] = '7aff676701cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('price', sa.DECIMAL(), nullable=False),
    sa.Column('stock_quantity', sa.Integer(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_index(op.f('ix_recommendations_id'), 'recommendations', ['id'], unique=False)
    op.create_unique_constraint('unique_service_report', 'recommendations', ['service_id', 'report_id'])
    op.create_foreign_key(None, 'recommendations', 'reports', ['report_id'], ['id'])
    op.create_foreign_key(None, 'recommendations', 'services', ['service_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recommendations', type_='foreignkey')
    op.drop_constraint(None, 'recommendations', type_='foreignkey')
    op.drop_constraint('unique_service_report', 'recommendations', type_='unique')
    op.drop_index(op.f('ix_recommendations_id'), table_name='recommendations')
    op.drop_table('products')
    # ### end Alembic commands ###
