"""update tenant subscription model

Revision ID: 7b5e793bcc1d
Revises: e6d08f0c84ae
Create Date: 2026-02-24 15:05:14.589019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7b5e793bcc1d'
down_revision: Union[str, Sequence[str], None] = 'e6d08f0c84ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant_subscriptions', sa.Column('approved_by', sa.Integer(), nullable=True))
    op.add_column('tenant_subscriptions', sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tenant_subscriptions', sa.Column('terminated_reason', sa.Text(), nullable=True))
    op.alter_column('tenant_subscriptions', 'activated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('tenant_subscriptions', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.create_foreign_key(None, 'tenant_subscriptions', 'users', ['approved_by'], ['id'])
    op.drop_column('tenant_subscriptions', 'is_active')
    op.alter_column('user_tenant_plans', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_tenant_plans', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.add_column('tenant_subscriptions', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tenant_subscriptions', type_='foreignkey')
    op.alter_column('tenant_subscriptions', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('tenant_subscriptions', 'activated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_column('tenant_subscriptions', 'terminated_reason')
    op.drop_column('tenant_subscriptions', 'approved_at')
    op.drop_column('tenant_subscriptions', 'approved_by')
    # ### end Alembic commands ###
