"""pls work

Revision ID: 88462ee28a56
Revises: c87365320259
Create Date: 2026-02-21 22:23:30.144895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '88462ee28a56'
down_revision: Union[str, Sequence[str], None] = 'c87365320259'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'fontkey') THEN
                CREATE TYPE fontkey AS ENUM ('f1', 'f2', 'f3', 'f4', 'f5');
            END IF;
        END
        $$;
        """
    )
    op.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'consultationstatus') THEN
                CREATE TYPE consultationstatus AS ENUM ('pending', 'scheduled', 'completed', 'rejected');
            END IF;
        END
        $$;
        """
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_details',
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('logo', sa.String(length=255), nullable=True),
    sa.Column('moto', sa.String(length=255), nullable=True),
    sa.Column('brand_color_primary', sa.String(length=7), nullable=True),
    sa.Column('brand_color_secondary', sa.String(length=7), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('slogan', sa.String(length=255), nullable=True),
    sa.Column('about_text', sa.String(length=1000), nullable=True),
    sa.Column('font_key', postgresql.ENUM('f1', 'f2', 'f3', 'f4', 'f5', name='fontkey', create_type=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('tenant_id')
    )
    op.create_table('consultation_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_name', sa.String(length=255), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date_of_request', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('preferred_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', postgresql.ENUM('pending', 'scheduled', 'completed', 'rejected', name='consultationstatus', create_type=False), nullable=False),
    sa.Column('sales_agent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sales_agent_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('tenant_subscriptions', sa.Column('membership_id', sa.Integer(), nullable=False))
    op.drop_constraint('tenant_subscriptions_membership_plan_id_fkey', 'tenant_subscriptions', type_='foreignkey')
    op.create_foreign_key(None, 'tenant_subscriptions', 'memberships', ['membership_id'], ['id'])
    op.drop_column('tenant_subscriptions', 'membership_plan_id')
    op.add_column('tenants', sa.Column('email', sa.String(length=255), nullable=False))
    op.add_column('tenants', sa.Column('licence_number', sa.String(length=255), nullable=False))
    op.create_index(op.f('ix_tenants_email'), 'tenants', ['email'], unique=True)
    op.create_index(op.f('ix_tenants_licence_number'), 'tenants', ['licence_number'], unique=True)
    op.drop_column('tenants', 'logo')
    op.drop_column('tenants', 'moto')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('moto', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('logo', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_tenants_licence_number'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_email'), table_name='tenants')
    op.drop_column('tenants', 'licence_number')
    op.drop_column('tenants', 'email')
    op.add_column('tenant_subscriptions', sa.Column('membership_plan_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tenant_subscriptions', type_='foreignkey')
    op.create_foreign_key('tenant_subscriptions_membership_plan_id_fkey', 'tenant_subscriptions', 'memberships', ['membership_plan_id'], ['id'])
    op.drop_column('tenant_subscriptions', 'membership_id')
    op.drop_table('consultation_requests')
    op.drop_table('tenant_details')
    # ### end Alembic commands ###
