"""add_tenant_slug_and_image

Revision ID: 8894f984316d
Revises: 7b5e793bcc1d
Create Date: 2026-02-24 16:54:42.379662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8894f984316d'
down_revision: Union[str, Sequence[str], None] = '7b5e793bcc1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant_details', sa.Column('image', sa.String(length=255), nullable=True))
    op.add_column('tenants', sa.Column('slug', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_column('tenants', 'slug')
    op.drop_column('tenant_details', 'image')
    # ### end Alembic commands ###
