"""update lead table

Revision ID: 95d03520a8fc
Revises: 8610bc6f16e9
Create Date: 2026-02-24 16:56:07.400527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95d03520a8fc'
down_revision: Union[str, Sequence[str], None] = '8610bc6f16e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('organization_name', sa.String(length=255), nullable=True))
    op.add_column('leads', sa.Column('contact_email', sa.String(length=255), nullable=True))
    op.add_column('leads', sa.Column('contact_phone', sa.String(length=50), nullable=True))
    op.add_column('leads', sa.Column('source', sa.String(length=100), nullable=True))
    op.add_column('leads', sa.Column('assigned_sales_user_id', sa.Integer(), nullable=True))
    op.drop_constraint('leads_tenant_id_fkey', 'leads', type_='foreignkey')
    op.create_foreign_key(None, 'leads', 'users', ['assigned_sales_user_id'], ['id'])
    op.drop_column('leads', 'company_name')
    op.drop_column('leads', 'phone')
    op.drop_column('leads', 'email')
    op.drop_column('leads', 'tenant_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('leads', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('leads', sa.Column('phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('leads', sa.Column('company_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.create_foreign_key('leads_tenant_id_fkey', 'leads', 'tenants', ['tenant_id'], ['id'])
    op.drop_column('leads', 'assigned_sales_user_id')
    op.drop_column('leads', 'source')
    op.drop_column('leads', 'contact_phone')
    op.drop_column('leads', 'contact_email')
    op.drop_column('leads', 'organization_name')
    # ### end Alembic commands ###
