"""add appointment status history

Revision ID: ae09cec4659c
Revises: 501450917fad
Create Date: 2026-02-24 03:42:56.777406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae09cec4659c'
down_revision: Union[str, Sequence[str], None] = '501450917fad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointment_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('old_status', sa.Enum('REQUESTED', 'CONFIRMED', 'COMPLETED', 'CANCELLED', name='appointment_status', create_type=False), nullable=True),
    sa.Column('new_status', sa.Enum('REQUESTED', 'CONFIRMED', 'COMPLETED', 'CANCELLED', name='appointment_status', create_type=False), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appointment_status_history')
    # ### end Alembic commands ###
