"""fix subscription plan references

Revision ID: afb71725c1c6
Revises: 52941afd21f8
Create Date: 2026-02-24 13:33:17.955256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'afb71725c1c6'
down_revision: Union[str, Sequence[str], None] = '52941afd21f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_plans',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('price', sa.Numeric(
                        precision=10, scale=2), nullable=False),
                    sa.Column('duration', sa.Integer(), nullable=False),
                    sa.Column('max_doctors', sa.Integer(), nullable=True),
                    sa.Column('max_patients', sa.Integer(), nullable=True),
                    sa.Column('max_departments', sa.Integer(), nullable=True),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('enrollments',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('tenant_id', sa.Integer(), nullable=False),
                    sa.Column('patient_user_id', sa.Integer(), nullable=False),
                    sa.Column('subscription_plan_id',
                              sa.Integer(), nullable=False),
                    sa.Column('created_by', sa.Integer(), nullable=False),
                    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'CANCELLED',
                                                'EXPIRED', name='enrollment_status'), nullable=False),
                    sa.Column('activated_at', sa.String(), nullable=True),
                    sa.Column('cancelled_at', sa.String(), nullable=True),
                    sa.Column('expires_at', sa.String(), nullable=True),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
                    sa.ForeignKeyConstraint(['patient_user_id'], [
                                            'patients.user_id'], ),
                    sa.ForeignKeyConstraint(['subscription_plan_id'], [
                        'subscription_plans.id'], ),
                    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('tenant_id', 'patient_user_id',
                                        name='uq_enrollment_patient_tenant')
                    )
    op.drop_constraint('tenant_subscriptions_membership_id_fkey',
                       'tenant_subscriptions', type_='foreignkey')
    op.execute("DROP TABLE IF EXISTS user_tenant_memberships")
    op.drop_table('memberships')
    op.add_column('tenant_subscriptions', sa.Column(
        'subscription_plan_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'tenant_subscriptions', 'subscription_plans', [
                          'subscription_plan_id'], ['id'])
    op.drop_column('tenant_subscriptions', 'membership_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant_subscriptions', sa.Column(
        'membership_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tenant_subscriptions', type_='foreignkey')
    op.create_foreign_key('tenant_subscriptions_membership_id_fkey',
                          'tenant_subscriptions', 'memberships', ['membership_id'], ['id'])
    op.drop_column('tenant_subscriptions', 'subscription_plan_id')
    op.create_table('memberships',
                    sa.Column('id', sa.INTEGER(),
                              autoincrement=True, nullable=False),
                    sa.Column('name', sa.VARCHAR(length=100),
                              autoincrement=False, nullable=False),
                    sa.Column('price', sa.NUMERIC(precision=10, scale=2),
                              autoincrement=False, nullable=False),
                    sa.Column('duration', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text(
                        'now()'), autoincrement=False, nullable=False),
                    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text(
                        'now()'), autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('id', name='memberships_pkey'),
                    sa.UniqueConstraint('name', name='memberships_name_key', postgresql_include=[
                    ], postgresql_nulls_not_distinct=False)
                    )
    op.create_table('user_tenant_memberships',
                    sa.Column('id', sa.INTEGER(),
                              autoincrement=True, nullable=False),
                    sa.Column('user_id', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('tenant_id', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text(
                        'now()'), autoincrement=False, nullable=False),
                    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text(
                        'now()'), autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(
                        ['tenant_id'], ['tenants.id'], name='user_tenant_memberships_tenant_id_fkey'),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['users.id'], name='user_tenant_memberships_user_id_fkey'),
                    sa.PrimaryKeyConstraint(
                        'id', name='user_tenant_memberships_pkey'),
                    sa.UniqueConstraint('user_id', 'tenant_id', name='uq_user_tenant',
                                        postgresql_include=[], postgresql_nulls_not_distinct=False)
                    )
    op.drop_table('enrollments')
    op.drop_table('subscription_plans')
    # ### end Alembic commands ###
