"""service model added

Revision ID: b9781aa86553
Revises: cfea3a45c558
Create Date: 2026-02-24 01:27:22.063886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9781aa86553'
down_revision: Union[str, Sequence[str], None] = 'cfea3a45c558'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('departments_name_key', 'departments', type_='unique')
    op.drop_index('ix_departments_name', table_name='departments')
    op.create_index(op.f('ix_departments_name'), 'departments', ['name'], unique=True)
    op.alter_column('tenant_departments', 'location',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_constraint('uq_tenant_department', 'tenant_departments', type_='unique')
    op.create_index(op.f('ix_tenant_departments_department_id'), 'tenant_departments', ['department_id'], unique=False)
    op.create_index(op.f('ix_tenant_departments_id'), 'tenant_departments', ['id'], unique=False)
    op.create_index(op.f('ix_tenant_departments_tenant_id'), 'tenant_departments', ['tenant_id'], unique=False)
    op.create_unique_constraint(None, 'tenant_departments', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tenant_departments', type_='unique')
    op.drop_index(op.f('ix_tenant_departments_tenant_id'), table_name='tenant_departments')
    op.drop_index(op.f('ix_tenant_departments_id'), table_name='tenant_departments')
    op.drop_index(op.f('ix_tenant_departments_department_id'), table_name='tenant_departments')
    op.create_unique_constraint('uq_tenant_department', 'tenant_departments', ['tenant_id', 'department_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('tenant_departments', 'location',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_index(op.f('ix_departments_name'), table_name='departments')
    op.create_index('ix_departments_name', 'departments', ['name'], unique=False)
    op.create_unique_constraint('departments_name_key', 'departments', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
