"""fix patient table

Revision ID: d3be20552ba7
Revises: f6ccdf8dcc2a
Create Date: 2026-02-26 16:58:49.677968

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d3be20552ba7"
down_revision: Union[str, Sequence[str], None] = "f6ccdf8dcc2a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _col_exists(table: str, column: str) -> bool:
    bind = op.get_bind()
    return bind.execute(
        sa.text(
            "SELECT EXISTS(SELECT 1 FROM information_schema.columns "
            "WHERE table_name = :t AND column_name = :c)"
        ),
        {"t": table, "c": column},
    ).scalar_one()


def _constraint_exists(name: str) -> bool:
    bind = op.get_bind()
    return bind.execute(
        sa.text("SELECT EXISTS(SELECT 1 FROM pg_constraint WHERE conname = :n)"),
        {"n": name},
    ).scalar_one()


def upgrade() -> None:
    """Upgrade schema."""
    if not _col_exists("appointments", "duration_minutes"):
        op.add_column(
            "appointments", sa.Column("duration_minutes", sa.Integer(), nullable=False)
        )
    if not _col_exists("patients", "tenant_id"):
        op.add_column("patients", sa.Column("tenant_id", sa.Integer(), nullable=False))
    if not _constraint_exists("uq_patients_tenant_user"):
        op.create_unique_constraint(
            "uq_patients_tenant_user", "patients", ["tenant_id", "user_id"]
        )
    # FK — create only if tenant_id column was just added (no FK yet)
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_fks = [fk["name"] for fk in inspector.get_foreign_keys("patients")]
    has_tenant_fk = any(
        fk
        for fk in inspector.get_foreign_keys("patients")
        if fk.get("referred_table") == "tenants"
    )
    if not has_tenant_fk:
        op.create_foreign_key(None, "patients", "tenants", ["tenant_id"], ["id"])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "patients", type_="foreignkey")
    op.drop_constraint("uq_patients_tenant_user", "patients", type_="unique")
    op.drop_column("patients", "tenant_id")
    op.drop_column("appointments", "duration_minutes")
    # ### end Alembic commands ###
