"""update doctor-tenant_department relationship

Revision ID: f6ccdf8dcc2a
Revises: 64d659958a52
Create Date: 2026-02-26 16:28:37.052146

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f6ccdf8dcc2a"
down_revision: Union[str, Sequence[str], None] = "64d659958a52"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tables = inspector.get_table_names()

    if "consultation_requests" in tables:
        op.drop_table("consultation_requests")

    doctor_cols = {c["name"] for c in inspector.get_columns("doctors")}
    if "tenant_department_id" not in doctor_cols:
        op.add_column(
            "doctors", sa.Column("tenant_department_id", sa.Integer(), nullable=False)
        )
        op.create_foreign_key(
            None, "doctors", "tenant_departments", ["tenant_department_id"], ["id"]
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "doctors", type_="foreignkey")
    op.drop_column("doctors", "tenant_department_id")
    op.create_table(
        "consultation_requests",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "tenant_name", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.Column(
            "contact_email", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "date_of_request",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "preferred_date",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "status",
            postgresql.ENUM(
                "pending",
                "scheduled",
                "completed",
                "rejected",
                name="consultationstatus",
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("sales_agent_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["sales_agent_id"],
            ["users.id"],
            name="consultation_requests_sales_agent_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="consultation_requests_pkey"),
    )
    # ### end Alembic commands ###
