"""add audit logs table

Revision ID: f8a7a307dd99
Revises: a1b2c3d4e5f6
Create Date: 2026-02-22 16:38:28.904219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8a7a307dd99'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_audit_logs',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('tenant_id', sa.Integer(), nullable=False),
                    sa.Column('event_type', sa.String(
                        length=50), nullable=False),
                    sa.Column('entity_name', sa.String(
                        length=50), nullable=False),
                    sa.Column('entity_id', sa.Integer(), nullable=True),
                    sa.Column('old_value', sa.JSON(), nullable=True),
                    sa.Column('new_value', sa.JSON(), nullable=True),
                    sa.Column('performed_by_user_id',
                              sa.Integer(), nullable=True),
                    sa.Column('performed_by_role', sa.String(), nullable=True),
                    sa.Column('ip_address', sa.String(
                        length=100), nullable=True),
                    sa.Column('reason', sa.String(length=500), nullable=True),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_tenant_audit_logs_tenant_id'),
                    'tenant_audit_logs', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenant_audit_logs_tenant_id'),
                  table_name='tenant_audit_logs')
    op.drop_table('tenant_audit_logs')
    # ### end Alembic commands ###
